kind: Secret
apiVersion: v1
metadata:
  name: #kubebench-name#
  annotations:
    chaimeleon.eu/kubebench: 'true'
  labels:
    chaimeleon.eu/kubebench: 'true'
data:
  container-password: ZEQ5ZFlhUnAxT011a0xRbHUzS1I=


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: #kubebench-name#
  labels:
    app.kubernetes.io/app-version: '3.6'
    app.kubernetes.io/instance: test2
    app.kubernetes.io/name: desktop-pytorch
    app.kubernetes.io/version: 2.3.1
    chaimeleon.eu/kubebench: 'true'
  annotations:
    chaimeleon.eu/persistentHomeMountPoint: /home/chaimeleon/persistent-home
    chaimeleon.eu/persistentSharedFolderMountPoint: /home/chaimeleon/persistent-shared-folder
    chaimeleon.eu/datasetsMountPoint: /home/chaimeleon/datasets
    chaimeleon.eu/datasetsIDs: a092a929-ef5b-41f2-93ee-9231c56beeb6
    chaimeleon.eu/kubebench: 'true'
    chaimeleon.eu/createGuacamoleConnection: 'true'
    chaimeleon.eu/datasetsIDs: a092a929-ef5b-41f2-93ee-9231c56beeb6
    chaimeleon.eu/guacamoleConnectionName: 2023-08-25-10-15-13---#kubebench-name#
    chaimeleon.eu/testingEnvironment: 'False'
    chaimeleon.eu/toolName: desktop-pytorch
    chaimeleon.eu/toolVersion: 2.3.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #kubebench-name#
  template:
    metadata:
      labels:
        app: #kubebench-name#
    spec:
      containers:
        - name: desktop-pytorch
          image: >-
            harbor.chaimeleon-eu.i3m.upv.es/chaimeleon-library/ubuntu_python_pytorch_desktop:3.6
          ports:
            - name: sshd
              containerPort: 2222
              protocol: TCP
            - name: vnc-gui
              containerPort: 5900
              protocol: TCP
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: #kubebench-name#
                  key: container-password
            - name: VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: #kubebench-name#
                  key: container-password
            - name: DATASETS_LIST
              value: a092a929-ef5b-41f2-93ee-9231c56beeb6
            - name: SSH_ENABLE_PASSWORD_AUTH
              value: 'true'
            - name: GATEWAY_PORTS
              value: 'true'
            - name: TCP_FORWARDING
              value: 'true'
          resources:
            limits:
              cpu: '2'
              memory: 7Gi
            requests:
              cpu: 900m
              memory: 7Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        chaimeleon.eu/target: desktops
      schedulerName: default-scheduler
      priorityClassName: processing-applications

---

kind: Service
apiVersion: v1
metadata:
  name: #kubebench-name#
  annotations:
    chaimeleon.eu/kubebench: 'true'
  labels:
    chaimeleon.eu/kubebench: 'true'
spec:
  ports:
    - name: sshd-svc
      protocol: TCP
      port: 2222
      targetPort: sshd
    - name: vnc-gui-svc
      protocol: TCP
      port: 5900
      targetPort: vnc-gui
  selector:
    app: #kubebench-name#
